Copyright (C) 2013, 2014 Steven Stewart-Gallus

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.

Linted -- TODO

* Port to --host=i686-w64-mingw32
* Ban assert in favour of LINTED_IMPOSSIBLE_ERROR
assert has problems with not evaluating arguments.
* Manage child process error streams and syslog logs
* Fix simulator use after free race on message queue
* Make unimq respect EINTR
Currently it uses condition variables which don't work well with
it. POSIX semaphores do however respect EINTR.
* Avoid deadlock where process blocks on sending message to shutdown process
* Think about whether to use -Wa,--noexecstack and -Wl,-z,noexecstack
I think I read somewhere that these force a nonexecutable stack but
that if things are done correctly that the shouldn't be happening
anyways. I believe what I really want is a -Wl,--warn-execstack
option.
* Make spawner forks check passed in sockets
Because the spawner forks off processes the current protocol isn't so
bad but there should be a little error checking.
* Don't do cargo cult security
This is pretty much impossible.

I'm just a young hacker playing around with technologies like
sandboxing. I have no real knowledge of security. I hope this project
is useful as a personal learning experience though.
* Don't do security theater
Security theater is when people do big and impressive things with
sandboxing but then conveniently forget a back door that lets
attackers in.

See cargo cult security for why this is impossible.
