Linted -- TODO

* Port to --host=i686-w64-mingw32
* Handle parent process death (causes SIGHUP) properly
* Have a better error handling scheme for processes
I need to be able signal failure from one process to another.
* Think about whether to use -Wa,--noexecstack and -Wl,-z,noexecstack
I think I read somewhere that these force a nonexecutable stack but
that if things are done correctly that the shouldn't be happening
anyways. I believe what I really want is a -Wl,--warn-execstack
option.
* Cleanup the ugly code in task.c
* Fix bug where the spawner can't close because it keeps a handle to itself
* Fix bug where forked processes don't check for bad stdin, stdout and stderr
* Make servers hand out the connection file descriptors not clients
The current way is inherently fragile and insecure.
* Don't do cargo cult security
This is pretty much impossible.

I'm just a young hacker playing around with technologies like
sandboxing. I have no real knowledge of security. I hope this project
is useful as a personal learning experience though.
