Linted -- TODO

* Port to --host=i686-w64-mingw32
* Handle parent process death (causes SIGHUP) properly
* Have a better error handling scheme for processes
I need to be able signal failure from one process to another.
* Think about whether to use -Wa,--noexecstack and -Wl,-z,noexecstack
I think I read somewhere that these force a nonexecutable stack but
that if things are done correctly that the shouldn't be happening
anyways. I believe what I really want is a -Wl,--warn-execstack
option.
* Fix spawner process shutdown
* Fix spawner process main loop stealing
The spawner process should probable explicitly use a callback for the
supervisor process startup instead of doing a fork and return. This
should also fix the bad stdin, stdout and stderr problems.
* Fix bug where forked processes don't check for bad stdin, stdout and stderr
* Make spawner forks check passed in sockets
Because the spawner forks off processes the current protocol isn't so
bad but there should be a little error checking.
* Don't do cargo cult security
This is pretty much impossible.

I'm just a young hacker playing around with technologies like
sandboxing. I have no real knowledge of security. I hope this project
is useful as a personal learning experience though.
