#! /usr/bin/env sh
# Copyright (C) 2015 Steven Stewart-Gallus
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

set -e
set -C
set -u

TARGET="$(printf -- '%s' "$0" | cut -d- -f 2-)"

SRCDIR="$(cd "$(dirname "$0")" && pwd)/../.."

exec "${SRCDIR}/configure"\
  --build="$("${SRCDIR}/build-aux/config.guess")"\
  --host="${TARGET}"\
  "$@"
