#! /usr/bin/env sh
# Copyright (C) 2015 Steven Stewart-Gallus
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

set -e
set -C
set -u

# Use the sysroot C compiler option to use this like a sandbox

: ${OS:='linux'}
: ${ABI:='gnu'}

if test "x${ARCH}" = x
then
    exit 1
fi


deps() {
    # This is an ugly hack to get autoconf working
    printf '%s\0' "libc6"
    printf '%s\0' "libc6-dev"

    case "${ARCH}-${OS}"-"${ABI}" in
	'aarch64-linux-gnu' | \
	'arm-linux-androideabi' | \
	'arm-linux-gnueabi' | \
	'arm-linux-gnueabihf' | \
	'i686-linux-android' | \
	'powerpc64le-linux-gnu' | \
	'powerpc-linux-gnu')
	    printf '%s\0' "gcc-${ARCH}-${OS}-${ABI}"
	    ;;

	'amd64-w64-mingw')
	    printf '%s\0' "mingw-w64-x86-64-dev"
	    ;;
	'i686-w64-mingw')
	    printf '%s\0' "mingw-w64-i686-dev"
	    ;;

	'i686-linux-musl' | 'amd64-linux-musl')
	    printf '%s\0' "musl-dev:${ARCH}"
	    ;;

	'i686-linux-gnu' | 'amd64-linux-gnu')
	    printf '%s\0' "libc6:${ARCH}"
	    printf '%s\0' "libc6-dev:${ARCH}"
	    printf '%s\0' "libcap-dev:${ARCH}"
	    printf '%s\0' "libegl1-mesa:${ARCH}"
	    printf '%s\0' "libegl1-mesa-dev:${ARCH}"
	    printf '%s\0' "libgl1-mesa-glx:${ARCH}"
	    printf '%s\0' "libgles2-mesa:${ARCH}"
	    printf '%s\0' "libgles2-mesa-dev:${ARCH}"
	    printf '%s\0' "libglib2.0-0:${ARCH}"
	    printf '%s\0' "libxcb1:${ARCH}"
	    printf '%s\0' "libxcb1-dev:${ARCH}"
	    printf '%s\0' "libxcb-xkb1:${ARCH}"
	    printf '%s\0' "libxcb-xkb-dev:${ARCH}"
	    printf '%s\0' "libxdmcp-dev:${ARCH}"
	    printf '%s\0' "libxkbcommon0:${ARCH}"
	    printf '%s\0' "libxkbcommon-dev:${ARCH}"
	    printf '%s\0' "libxkbcommon-x11-0:${ARCH}"
	    printf '%s\0' "libxkbcommon-x11-dev:${ARCH}"
	    printf '%s\0' "linux-libc-dev:${ARCH}"

	    printf '%s\0' "libdrm2:${ARCH}"
	    printf '%s\0' "libffi6:${ARCH}"
	    printf '%s\0' "libgbm1:${ARCH}"
	    printf '%s\0' "libglapi-mesa:${ARCH}"
	    printf '%s\0' "libwayland-client0:${ARCH}"
	    printf '%s\0' "libwayland-server0:${ARCH}"
	    printf '%s\0' "libx11-6:${ARCH}"
	    printf '%s\0' "libx11-dev:${ARCH}"
	    printf '%s\0' "libx11-xcb1:${ARCH}"
	    printf '%s\0' "libxcb-dri2-0:${ARCH}"
	    printf '%s\0' "libxcb-xfixes0:${ARCH}"
	    printf '%s\0' "x11proto-core-dev"
	    ;;

	*)
	    ;;
    esac
}

mkdir -p var/cache/builddeps
(cd var/cache/builddeps && deps | xargs -0 -- apt-get download) || :

for II in var/cache/builddeps/*.deb
do
    dpkg-deb -x "$II" ./
done
