#! /usr/bin/env sh
# Copyright (C) 2015 Steven Stewart-Gallus
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

set -e
set -C
set -u

# Use the sysroot C compiler option to use this like a sandbox

if test "x${ARCH}" = x
then
    exit 1
fi

deps() {
    printf '%s\n' "libc6:${ARCH}"
    printf '%s\n' "libc6-dev:${ARCH}"
    printf '%s\n' "libcap-dev:${ARCH}"
    printf '%s\n' "libegl1-mesa:${ARCH}"
    printf '%s\n' "libegl1-mesa-dev:${ARCH}"
    printf '%s\n' "libgl1-mesa-glx:${ARCH}"
    printf '%s\n' "libgles2-mesa:${ARCH}"
    printf '%s\n' "libgles2-mesa-dev:${ARCH}"
    printf '%s\n' "libglib2.0-0:${ARCH}"
    printf '%s\n' "libxcb1:${ARCH}"
    printf '%s\n' "libxcb1-dev:${ARCH}"
    printf '%s\n' "libxcb-xkb-dev:${ARCH}"
    printf '%s\n' "libxdmcp-dev:${ARCH}"
    printf '%s\n' "libxkbcommon-dev:${ARCH}"
    printf '%s\n' "libxkbcommon-x11-dev:${ARCH}"
    printf '%s\n' "linux-libc-dev:${ARCH}"

    printf '%s\n' "libdrm2:${ARCH}"
    printf '%s\n' "libffi6:${ARCH}"
    printf '%s\n' "libgbm1:${ARCH}"
    printf '%s\n' "libglapi-mesa:${ARCH}"
    printf '%s\n' "libwayland-client0:${ARCH}"
    printf '%s\n' "libwayland-server0:${ARCH}"
    printf '%s\n' "libx11-6:${ARCH}"
    printf '%s\n' "libx11-dev:${ARCH}"
    printf '%s\n' "libx11-xcb1:${ARCH}"
    printf '%s\n' "libxcb-dri2-0:${ARCH}"
    printf '%s\n' "libxcb-xfixes0:${ARCH}"
    printf '%s\n' "x11proto-core-dev"
}

mkdir -p var/cache/builddeps
(cd var/cache/builddeps && apt-get download $(deps))

for II in var/cache/builddeps/*.deb
do
    dpkg-deb -x "$II" ./
done
