#! /usr/bin/env sh
# Copyright (C) 2015 Steven Stewart-Gallus
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

set -e
set -C
set -u

ROOT="$(cd "$(dirname "$0")" && pwd)"

exec "${ROOT}/../configure"\
     --build="$("${ROOT}/../build-aux/config.guess")"\
     --host=x86_64-w64-mingw32\
     CC=x86_64-w64-mingw32-gcc\
     $@
