#! /usr/bin/env sh

set -e
set -C
set -u

ROOT="$(cd "$(dirname "$0")" && pwd)"

exec "${ROOT}/../configure"\
     --build="$("${ROOT}/../build-aux/config.guess")"\
     --host=none-none-none\
     --disable-shared\
     --enable-debug\
     CC='cgcc -std=c99'\
     CPPFLAGS="-U_FORTIFY_SOURCE -U__OPTIMIZE__ -U_OPTIMIZE_SIZE__"\
     $@
