#! /usr/bin/env sh
# Copyright (C) 2015 Steven Stewart-Gallus
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

set -e
set -C
set -u

ROOT="$(cd "$(dirname "$0")" && pwd)"

exec "${SRC}/scripts/archs/configure-x86_64-linux-gnu"\
     --disable-shared\
     --enable-debug\
     CC='cgcc -std=c99'\
     CPPFLAGS="-U_FORTIFY_SOURCE -U__OPTIMIZE__ -U_OPTIMIZE_SIZE__"\
     $@
