#! /usr/bin/env sh

set -e
set -C
set -u

ROOT="$(cd "$(dirname "$0")" && pwd)"

exec "${ROOT}/../configure"\
     --build="$("${ROOT}/../build-aux/config.guess")"\
     --host=none-none-none\
     --disable-shared\
     CC="${ROOT}/json-cc"\
     $@
