#! /usr/bin/env sh

set -e
set -C
set -u

ROOT="$(cd "$(dirname "$0")" && pwd)"
SRC="${ROOT}/.."
JSON_CC="${ROOT}/json-cc.py"

: ${CC:=gcc}

exec "${SRC}/configure"\
     --build="$("${SRC}/build-aux/config.guess")"\
     --host=none-none-none\
     --disable-shared\
     --enable-debug\
     CC="${JSON_CC} ${CC}"\
     $@
