#! /usr/bin/env sh
# Copyright (C) 2015 Steven Stewart-Gallus
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

set -e
set -C
set -u

ROOT="$(cd "$(dirname "$0")" && pwd)"
SRC="${ROOT}/.."
JSON_CC="${ROOT}/json-cc.py"

: ${CC:=gcc}

exec "${SRC}/configure"\
     --build="$("${SRC}/build-aux/config.guess")"\
     --host=none-none-none\
     --disable-shared\
     --enable-debug\
     --enable-posix-api\
     --enable-x11-api\
     CC="${JSON_CC} ${CC}"\
     $@
