#! /usr/bin/env sh
# Copyright (C) 2015 Steven Stewart-Gallus
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.
go() {
	# This is a description of a specific build product and not general
	# compilation.  Most people should not use this file.
	set -e
	set -C
	set -u

	export POSIXLY_CORRECT=1
	export LC_ALL='C.UTF-8'

	BASENAME="$(basename -- "$0")"

	while getopts 'h' OPT
	do
		case "${OPT}" in
		h)
			help
			return
			;;

		\?)
			printf -- 'Invalid option: -%s\n' "${OPTARG}"  >&2
			help >&2
			return 1
			;;
		esac
	done

	if test "$#" -lt 1
	then
		help >&2
		return 1
	fi
	COMMAND="$1"
	shift

	case "${COMMAND}" in
	'fetch-source')
		source "$@"
		;;

	'fetch-dependencies')
		deps "$@"
		;;

	'configure')
		configure "$@"
		;;

	'build')
		build "$@"
		;;

	*)
		help >&2
		return 1
		;;
	esac
}

help()
{
	printf -- '%s TASK\n' "${BASENAME}"
}

source()
{
	if test "$#" -ne 1
	then
		help >&2
		return 1
	fi
	SRCDIR="$1"
	shift

	mkdir -p "${SRCDIR}/linted"
	git clone --quiet --depth 1 --branch master -- 'git@gitlab.com:linted/linted.git' "${SRCDIR}/linted"
	autoreconf -ivf -Wall "${SRCDIR}/linted"
}

configure()
{
	if test "$#" -ne 3
	then
		help >&2
		return 1
	fi
	SRCDIR="$1"
	DEPDIR="$2"
	BUILDDIR="$3"
	shift 3

	mkdir -p "${BUILDDIR}/linted"
	CONFIGURE="$(realpath "${SRCDIR}/linted/configure-defaults")"

	DEPDIR="$(realpath "${DEPDIR}")"
	(
	cd "${BUILDDIR}/linted"
	"${CONFIGURE}" --with-sysroot="${DEPDIR}"
	)
}

build()
{
	if test "$#" -ne 1
	then
		help >&2
		return 1
	fi
	BUILDDIR="$1"
	shift


	make --silent -C "${BUILDDIR}/linted"
	make --silent install -C "${BUILDDIR}/linted" prefix="$(realpath "${BUILDDIR}/tarball")"
	(cd "${BUILDDIR}" && tar --mtime=0 --numeric-owner --group=root --owner=root -c -f 'tarball.tar' -C tarball -- .)
	gzip -n -9 -f -- "${BUILDDIR}/tarball.tar"
}

deps()
{
	if test "$#" -ne 1
	then
		help >&2
		return 1
	fi
	DEPDIR="$1"
	shift

	mkdir -p "${DEPDIR}/var/cache/builddeps"
	(cd "${DEPDIR}/var/cache/builddeps" && printdeps | xargs -0 -- apt-get download --quiet) || :

	for II in "${DEPDIR}"/var/cache/builddeps/*.deb
	do
	dpkg-deb -x "$II" "${DEPDIR}"
	done
}

printdeps() {
	: ${ARCH:='amd64'}
	: ${OS:='linux'}
	: ${ABI:='gnu'}

	# This is an ugly hack to get autoconf working
	printf '%s\0' 'libc6'
	printf '%s\0' 'libc6-dev'

	printf '%s\0' 'x11proto-core-dev'
	printf '%s\0' "x11proto-damage-dev"
	printf '%s\0' "x11proto-fixes-dev"
	printf '%s\0' "x11proto-kb-dev"
	printf '%s\0' "x11proto-xext-dev"
	printf '%s\0' "x11proto-xf86vidmode-dev"

	case "${ABI}" in
	'dietlibc')
		printf '%s\0' 'dietlibc-dev'
		;;

	*)
		;;
	esac

	case "${ARCH}-${OS}-${ABI}" in
	'aarch64-linux-gnu' | \
		'arm-linux-androideabi' | \
		'arm-linux-gnueabi' | \
		'arm-linux-gnueabihf' | \
		'i686-linux-android' | \
		'powerpc64le-linux-gnu' | \
		'powerpc-linux-gnu')
		printf '%s\0' "gcc-${ARCH}-${OS}-${ABI}"
		;;

	*)
		;;
	esac

	case "${ARCH}-${OS}-${ABI}" in
	'arm-linux-gnueabihf')
		printf '%s\0' 'libc6-dev-armhf-cross'
		;;

	'powerpc-linux-gnu')
		printf '%s\0' 'libc6-dev-powerpc-cross'
		;;

	'aarch64-linux-gnu')
		printf '%s\0' 'libc6-dev-arm64-cross'
		;;

	'arm-linux-gnueabi')
		printf '%s\0' 'libc6-dev-armel-cross'
		;;

	'powerpc64le-linux-gnu')
		printf '%s\0' 'libc6-dev-ppc64el-cross'
		;;

	'amd64-w64-mingw')
		printf '%s\0' 'mingw-w64-x86-64-dev'
		;;
	'i686-w64-mingw')
		printf '%s\0' 'mingw-w64-i686-dev'
		;;

	'i686-linux-musl' | 'amd64-linux-musl')
		printf '%s\0' "musl-dev:${ARCH}"
		;;

	*)
		;;
	esac

	case "${ARCH}" in
		'i386' | 'amd64')

		case "${OS}" in
		'linux')
			printf '%s\0' "linux-libc-dev:${ARCH}"
			;;
		*)
			;;
		esac

		case "${ARCH}-${OS}-${ABI}" in
		'i386-linux-gnu' | 'amd64-linux-gnu')
			printf '%s\0' "libc6:${ARCH}"
			printf '%s\0' "libc6-dev:${ARCH}"
			printf '%s\0' "libcap-dev:${ARCH}"
			printf '%s\0' "libegl1-mesa:${ARCH}"
			printf '%s\0' "libegl1-mesa-dev:${ARCH}"
			printf '%s\0' "libgl1-mesa-glx:${ARCH}"
			printf '%s\0' "libgles2-mesa:${ARCH}"
			printf '%s\0' "libgles2-mesa-dev:${ARCH}"
			printf '%s\0' "libglib2.0-0:${ARCH}"
			printf '%s\0' "libpulse0:${ARCH}"
			printf '%s\0' "libpulse-dev:${ARCH}"
			printf '%s\0' "libxcb1:${ARCH}"
			printf '%s\0' "libxcb1-dev:${ARCH}"
			printf '%s\0' "libxcb-xkb1:${ARCH}"
			printf '%s\0' "libxcb-xkb-dev:${ARCH}"
			printf '%s\0' "libxdmcp-dev:${ARCH}"
			printf '%s\0' "libxkbcommon0:${ARCH}"
			printf '%s\0' "libxkbcommon-dev:${ARCH}"
			printf '%s\0' "libxkbcommon-x11-0:${ARCH}"
			printf '%s\0' "libxkbcommon-x11-dev:${ARCH}"

			printf '%s\0' "libasyncns0:${ARCH}"
			printf '%s\0' "libcap2:${ARCH}"
			printf '%s\0' "libdbus-1-3:${ARCH}"
			printf '%s\0' "libdrm2:${ARCH}"
			printf '%s\0' "libdrm-dev:${ARCH}"
			printf '%s\0' "libffi6:${ARCH}"
			printf '%s\0' "libflac8:${ARCH}"
			printf '%s\0' "libgbm1:${ARCH}"
			printf '%s\0' "libglapi-mesa:${ARCH}"
			printf '%s\0' "libjson-c2:${ARCH}"
			printf '%s\0' "libogg0:${ARCH}"
			printf '%s\0' "libpthread-stubs0-dev:${ARCH}"
			printf '%s\0' "libsndfile1:${ARCH}"
			printf '%s\0' "libvorbis0a:${ARCH}"
			printf '%s\0' "libvorbisenc2:${ARCH}"
			printf '%s\0' "libwayland-client0:${ARCH}"
			printf '%s\0' "libwayland-server0:${ARCH}"
			printf '%s\0' "libwrap0:${ARCH}"
			printf '%s\0' "libx11-6:${ARCH}"
			printf '%s\0' "libx11-dev:${ARCH}"
			printf '%s\0' "libx11-xcb1:${ARCH}"
			printf '%s\0' "libx11-xcb-dev:${ARCH}"
			printf '%s\0' "libxau6:${ARCH}"
			printf '%s\0' "libxau-dev:${ARCH}"
			printf '%s\0' "libxcb-dri2-0:${ARCH}"
			printf '%s\0' "libxcb-dri2-0-dev:${ARCH}"
			printf '%s\0' "libxcb-dri3-dev:${ARCH}"
			printf '%s\0' "libxcb-glx0-dev:${ARCH}"
			printf '%s\0' "libxcb-present-dev:${ARCH}"
			printf '%s\0' "libxcb-sync-dev:${ARCH}"
			printf '%s\0' "libxcb-xfixes0:${ARCH}"
			printf '%s\0' "libxcb-xfixes0-dev:${ARCH}"
			printf '%s\0' "libxdamage-dev:${ARCH}"
			printf '%s\0' "libxdmcp6:${ARCH}"
			printf '%s\0' "libxext-dev:${ARCH}"
			printf '%s\0' "libxfixes-dev:${ARCH}"
			printf '%s\0' "libxkbcommon-x11-dev:${ARCH}"
			printf '%s\0' "libxshmfence-dev:${ARCH}"
			printf '%s\0' "libxxf86vm-dev:${ARCH}"
			;;

		*)
			;;
		esac
		;;

	*)
		;;
	esac
}

realpath()
{
	printf -- '%s/%s' "$(cd "$(dirname "$1")" && pwd)" "$(basename "$1")"
}

go "$@"
