#! /usr/bin/env sh
# Copyright (C) 2015 Steven Stewart-Gallus
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.

set -e
set -C
set -u

ldd "$@" | cut -f3 -d' ' | tail -n +2 | { while read REPLY; do test -z "${REPLY}" || dpkg -S "${REPLY}"; done } | sort
