#! /usr/bin/env sh

set -e
set -C
set -u

SCRIPTS="$(cd "$(dirname "$0")" && pwd)"
BINARY="$1"

: ${LINTED_CPPCHECK:=cppcheck}

source_files() {
    "${SCRIPTS}/json-cc-files" "${BINARY}"
}

"${LINTED_CPPCHECK}"\
    '--quiet'\
    '--enable=all'\
    '--suppress=resourceLeak'\
    '--suppress=variableScope'\
    '--suppress=sizeofwithsilentarraypointer'\
    '--suppress=uninitvar'\
    '--template={file}:{line}: ({id}) {message}'\
    $(source_files)
