#! /usr/bin/env sh

set -e
set -C
set -u

SCRIPTS="$(cd "$(dirname "$0")" && pwd)"
BINARY="$1"

: ${LINTED_FRAMA_C:=frama-c}

source_cflags() {
    for II in $("${SCRIPTS}/json-cc-flags" "${BINARY}"); do
        echo -cpp-extra-args="${II}"
    done
}

frama_c_stdlib() {
    echo -cpp-extra-args="-I$("${LINTED_FRAMA_C}" -print-share-path)/libc"
}

source_files() {
    "${SCRIPTS}/json-cc-files" "${BINARY}"
}


"${LINTED_FRAMA_C}"\
    -quiet\
    -journal-disable\
    -pp-annot\
    -machdep x86_64\
    -warn-signed-downcast\
    -warn-unsigned-downcast\
    -warn-unsigned-overflow\
    -warn-decimal-float none\
    -cpp-extra-args='-C'\
    $(source_cflags)\
    $(frama_c_stdlib)\
    $(source_files)
